#!/bin/bash
# Prüft, ob das erste Argument der Funktion der Name eines Verzeichniseintrages ist
entry_exists() {
    if test -e  $1  2>/dev/null
    then
            return 0
    fi
        return 1
}

export -f entry_exists


# Prüft, ob für das erste Argument der Funktion Schreibrecht besteht
is_writable() {
    if test -w  $1  2>/dev/null
    then
            return 0
    fi
        return 1
}

export -f is_writable


# Prüft, ob für das erste Argument der Funktion Ausführungsrecht besteht
is_executable() {
    if test -w  $1  2>/dev/null
    then
            return 0
    fi
        return 1
}

export -f is_executable

# Prüft, ob das erste Argument der Funktion der Name eines Verzeichnisses ist
is_dir() {
    if test -d  $1  2>/dev/null
    then
            return 0
    fi
        return 1
}

export -f is_dir

# Prüft, ob das erste Argument der Funktion der Name einer normalen Datei ist
is_normal_file() {
  if test -f  $1  2>/dev/null
  then
    return 0
  fi
  return 1
}

export -f is_normal_file

# Prüft, ob das erste Argument der Funktion der Name
# eines Verzeichnisses ist und ob Schreibrecht besteht
# nutzt die Funktionen is_dir und is_writable
is_writable_dir() {
  if is_dir $1 && is_writable $1
  then
    return 0
  fi
  return 1
}

export -f is_writable_dir

kontrolle() {
        if [ -d ${1} ];then
#               echo ${1} does exist

                if [ ! -x ${1} ];then
                echo ${1} ls not permitted
                else
                echo ${1} ls permitted
                fi
                if [ ! -w ${1} ];then
                echo ${1} create files not permitted.
                else
                echo ${1} create files permitted.
                fi
        else
                echo ${1} folder does not exist.
                exit 3
        fi
}
export -f kontrolle
